sonar.projectKey=pts_pts-frontend_5a620d8a-c751-41b9-b315-584bfcc65a46
sonar.qualitygate.wait=true
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.exclusions=**/*.test.ts,**/*.test.tsx,./src/__mocks__/**,.next/**
